FROM node:22-alpine

WORKDIR /app

RUN npm install -g bun

COPY --chown=node:node package.json bun.lock ./
USER node
RUN bun install

COPY --chown=node:node . .

CMD ["bun", "dev", "--hostname", "0.0.0.0", "--port", "3500"]
